### ISSUE TITLE
Valor por defecto de numero_registro en 0

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/rnc_app#101]
Cuando un usuario crea una nueva colección se debe colocar el número por defecto en 0 para evitar problemas en la integridad de los datos

**Comment by jag2kn** [comment]
Se valida que esta en la url de creación de colección y se coloca este dato en 0 y además se deja bloqueado para la edición del usuario

**Comment by AngelaCelis** [comment]
Solved by Lumon.
