### ISSUE TITLE
Validación de campos de formulario de colecciones

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/rnc_app#102]
Se generan muchos errores en creación/actualización y validación del formulario para las colecciones por parte del usuario y del administrador.

Esto genera errores de consulta en base de datos y errores 500

**Comment by jag2kn** [comment]
Se implementó validación en los campos sistematización y catalogación, y tipo de preservación

**Comment by AngelaCelis** [comment]
Solved by Lumon.
