### ISSUE TITLE
Add captcha to request account form

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/rnc_app#2]
Please add captcha validation to the "request account" form

**Comment by danipilze** [comment]
is this done already, right?

**Comment by danipilze** [comment]
@andresciceri ?

**Comment by andresciceri** [comment]
The captcha validation can't be used inside these forms because the forms are used in other places when the user is logged and the framework can't difference the two situations, the solution is to create 2 forms.

**Comment by danipilze** [comment]
since the captcha in the login form is already made, I'm closing the issue.
