### ISSUE TITLE
In front end doesnt view the field "Colección a registrar"

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/rnc_app#21]
When user requests credential filled the field "Colección a registrar"

![image](https://cloud.githubusercontent.com/assets/16558682/12646394/bc8b08d8-c59d-11e5-9434-cb3746740724.png)

But, I cant see in the front end.

**Comment by jdmartinez89** [comment]
Solved either by Lumon or Hugo in the latest Update, say 6th of May 2016
