### ISSUE TITLE
New fields for RNC

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/rnc_app#24]
Hi guys,

Please for the new section "Curadores" in the RNC, please include:

Nombre: -required- -unstructured-
Cargo: -required- -unstructured-
Grupo biológico: -required- -structured- its the same that "información básica"
Subgrupo biológico: -required- -structured- its the same that "información básica" with the option "otro"
Correo electrónico: -required- -unstructured-  
Teléfono de contacto: -optional- 
Página web: -optional- Message i: Se sugieren enlaces al curriculum u otras relacionadas con la trayectoria académica o de investigación del curador. 

The section "Curadores" is after "Información básica" and its necessary be able add more than one.

Thanks!

Karen

**Comment by andresciceri** [comment]
The new form was created and is working in production version.
