### ISSUE TITLE
Error: the collection 196 Colección Hidrobiologica del Choco now appear like collection 0

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/rnc_app#25]
Hi Andrés,

The collection 196 now appears like collection 0, I dont know what happen, because collection 0 doesnt exist. 

Thanks

**Comment by adrisoacha** [comment]
Hi Andrés,

This is important, is a error and the user cant to update the collection.

Thanks,

Karen

**Comment by andresciceri** [comment]
The collection was updated with the right number collection.
