### ISSUE TITLE
Error: when users modify an update-request form, they can´t delete previously uploaded files

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/rnc_app#26]
Hi Andrés,

The form sends by user doesnt have the option for remove or replace a pdf archive:

![image](https://cloud.githubusercontent.com/assets/16558682/12886124/39a648a2-ce39-11e5-8700-338ebcc2a7a7.png)

This option it is necessary for users than need modify the attachments and they send again the form.

Thank you,

Karen

**Comment by jdmartinez89** [comment]
This issue is still pending

**Comment by jag2kn** [comment]
Se colocó un botón para poder eliminar los archivos anteriores, tanto en admin como en el usuario

**Comment by AngelaCelis** [comment]
Solved by Lumon.
