### ISSUE TITLE
Error persists collection 197

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/rnc_app#32]
Error persists @andresciceri 

El usuario dice:
Como vera la primera imagen es del campo de curador pero dice leyendo (loading) y en el día de ayer pensé que no había guardado y lo documente nuevamente, y cuando entre aparecía dos veces pero con la información incompleta. pero hoy ya no sale nada.
Las otras dos imágenes corresponden a los pantallas que me salían ayer y hoy al dar clic en guardar. lo mismo le sale a mi compañera curadora de la colección hidrobiológica.

![image](https://cloud.githubusercontent.com/assets/16558682/13149577/ef72bab4-d62f-11e5-919a-c5881f0a3c3c.png)

![image](https://cloud.githubusercontent.com/assets/16558682/13149539/cf230d86-d62f-11e5-9d31-9a395cf90b0b.png)

![image](https://cloud.githubusercontent.com/assets/16558682/13149557/e1c7d7d2-d62f-11e5-9fbc-bcf127e0ae85.png)

**Comment by andresciceri** [comment]
Please check with the user if this error continue happens or not.

**Comment by jdmartinez89** [comment]
This issue seems to be related to using MacOs or Safari browser. All related to the UTCH collections

**Comment by danipilze** [comment]
@jdmartinez89 which browser?

**Comment by jdmartinez89** [comment]
Browser: Chrome
This issue is happening again. When visualizing the update request I get the following message:
![image](https://cloud.githubusercontent.com/assets/17710971/15556051/64d005ca-2291-11e6-8bb5-2beb14911c0b.png)

**Comment by jdmartinez89** [comment]
Same just happened for collection 201:
![image](https://cloud.githubusercontent.com/assets/17710971/15556120/e45d8510-2291-11e6-8900-a6a391a3a287.png)

**Comment by danipilze** [comment]
ya veo, pero el error es distinto

**Comment by jdmartinez89** [comment]
lo reporto como otro error?
