### ISSUE TITLE
Error: no es posible avanzar en el desarrollo de RNC 2.0

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/rnc_app#37]
- Los controladores que utilizan el modelo Registros_update fallan debido a que el nombre del archivo es diferente al que se requiere en la convencion del framework
- En el formulario de crear Entidad el formulario falla porque esta buscando en POST el indice 'usuario_id'

**Comment by andresciceri** [comment]
The bug was solved and updated in the Github Repo.
