### ISSUE TITLE
Bad notification label for user requests

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#42]
When a user request is answered by the admin, the automatic email sent to rnc is named: "Aprobación de solicitud sistema RNC". I suggest it reads: "Respuesta a solicitud sistema RNC". This way it doesn´t create confusion with negative responses

**Comment by jag2kn** [comment]
Se cambiaron los textos

**Comment by AngelaCelis** [comment]
Solved by Lumon.
