### ISSUE TITLE
Creación de filtro para nueva versión del RNC

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/rnc_app#43]
"Hicimos la revision del filtro para colecciones biológicas y vemos que en la base de datos no existe una tabla en la que se encuentren los grupos taxonómicos para que sea similar al mapa de Australia. En la tabla de tipo de coleccion existen los datos que se muestran en el pantallazo, pero son un poco confusos para el filtro, por lo tanto quedo atenta a tu instruccion para ver como lo vamos a realizar."

**Comment by andresciceri** [comment]
Today i was talking with the Lumon's Developer and I solved his questions about the relation entities in the database
