### ISSUE TITLE
The Bitacora generation tab for admin does not have a collection type checkbox

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#45]
The Bitacora generation tab for admin does not have a collection type "Tipo de colección" checkbox, so when the file is generated the admin can not filter this information, I suggest adding this checkbox option in the "Información básica de la colección" section

**Comment by jag2kn** [comment]
Se colocó el checkbox "Tipo de Colección" y se agregó la funcionalidad en el servidor para incluir en el reporte generado esta información

**Comment by AngelaCelis** [comment]
Solved by Lumon.
