### ISSUE TITLE
Nuevos lenguajes controlados

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#46]
The new languages for the RNC collection update are shown in the attached file, 
[lenguajes para actualizar.xlsx.xlsx](https://github.com/SIB-Colombia/rnc_app/files/167146/lenguajes.para.actualizar.xlsx.xlsx)
Please contact me if any doubts arise.

**Comment by jdmartinez89** [comment]
For the field "Tipo de colección" it should ideally be represented by a checkbox list, with multiple answers.

**Comment by jag2kn** [comment]
Se hicieron los cambios cambios posibles en los 3 lugares de lenguajes controlados,

cuando no se puede cambiar se dejo en amarillo, ya que los datos deben ser validados por los titulares o por el Humboldt

https://docs.google.com/spreadsheets/d/1u1rheni8x6lMeb0wF3OSCBtUkRWuOwrcMWO-1P119HI/edit?ts=589e1e0b#gid=416125638


Sobre el comentario:

"For the field "Tipo de colección" it should ideally be represented by a checkbox list, with multiple answers."

Para este caso NO se hizo este cambio, ya que se genera un impacto muy fuerte:
 * Base datos, el tipo de colección es un campo, tocaría hacer una tabla nueva y nuevas relaciones
 * Modelos, toca modificar los modelos de datos en YII
 * Reportes, en los reportes toca modificar la consulta
 * Uso del formulario, toca modificar el como se recibe y visualiza la información

**Comment by AngelaCelis** [comment]
Solved by Lumon.
