### ISSUE TITLE
Error: when colletion 182 tries to uptade, the changes are not stored.

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#47]
The people updating collection No. 182 have been complaining about the imposibility of updating ther collection information. We signed ourselves with their credentials and no changes were seen once we tried to update the collection information. The error is so far specific to the named collection.

**Comment by jdmartinez89** [comment]
Corporación Centro de Investigación en Palma de Aceite	800145882	Wr00FCh

**Comment by andresciceri** [comment]
This collection can be updated now. Please try again.
