### ISSUE TITLE
Error: when reviewing the collection 197 update an error message for the curators pops up

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#51]
Error: when reviewing the collection 197 update an error message for the curators pops up. See the following error code message:

![image](https://cloud.githubusercontent.com/assets/17710971/14108864/d546f578-f584-11e5-8954-5aae0a47fd36.png)

When you look at the curators tab you see the list is constantly trying to load:

![image](https://cloud.githubusercontent.com/assets/17710971/14109464/c6f78336-f587-11e5-9ec8-5844c5a4a928.png)

**Comment by andresciceri** [comment]
This bug was solved.

**Comment by jdmartinez89** [comment]
@danipilze This is the one I was thinking, it is the same right?
