### ISSUE TITLE
Error: When trying to activate a registration form in the admin mode

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#55]
While being in the admin mode:

I search for any collection, and I click on the button _Activar Registro_ in the following url http://rnc.humboldt.org.co/admin/index.php/registros/viewDetail/811

the following message appears:
![image](https://cloud.githubusercontent.com/assets/17710971/15187984/263edd64-1769-11e6-901e-090ea0eb32a8.png)

This should not happen, modifying a users information should be possible from the admin tab.
The message that appears makes no sense: We are not trying to cancel de collection, we are trying to reopen de form in order to modify information.

**Comment by danipilze** [comment]
I got a different message

![seleccion_165](https://cloud.githubusercontent.com/assets/3705866/15302675/d077982a-1b79-11e6-8444-bca78c767f97.png)

**Comment by jdmartinez89** [comment]
Ok so I tried this on other collections and some work and others don´t. No. 077 works, but No. 139 and No. 192 do not work properly. I don´t know what can be driving this difference in bevahior I will try others and report.

**Comment by jag2kn** [comment]
Linea 2218 de ⁠⁠⁠Registrocontoller, evaluar cual es la respuesta del CActiveRecord

**Comment by jag2kn** [comment]
El campo Latitud y Longitud estaban en NULL para este registro, se hizo validación de estos campos colocando valor por defecto ya que es requerido en:
 * Latitud  = 4
 * Longitud = -74

**Comment by AngelaCelis** [comment]
Solved by Lumon.
