### ISSUE TITLE
Error when dowloading Curators detailed list

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#56]
Error for curators directory:
No se puede acceder a este sitio web
Es posible que la página web http://rnc.humboldt.org.co/admin/index.php/reporte/reporteCurador esté temporalmente inactiva o que se haya trasladado definitivamente a otra dirección.
ERR_INVALID_RESPONSE
![image](https://cloud.githubusercontent.com/assets/17710971/15215917/77551180-181a-11e6-8025-d9b166b76ef7.png)

**Comment by jag2kn** [comment]
Faltaba hacer la instalación de la libreria php-xml para la versión instalada de php que estaba por fuera de los repositorios de Centos habilitados en el sistema.

Se activa el repositorio y se instala la librería

**Comment by AngelaCelis** [comment]
Este error esta duplicado con el error #83 que ya se encuentra en la lista de open issues.
