### ISSUE TITLE
Error when a collection gets its update approval, the collections certificate is no longer uploaded automatically

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#60]
The certificate is generated automatically and sent via email, but it is no longer uploaded de the certificates the collection has online.

**Comment by jag2kn** [comment]
Cuando se genera un certificado se hace una copia en la carpeta ```rnc_files/Registro_Colecciones_Biologicas_Historicos/XXX_ACRONIMO/1_Registro_Actualizacion```

donde XXX corresponde a el ```numero_registro``` asignado

**Comment by AngelaCelis** [comment]
Revisado
