### ISSUE TITLE
Error: When collection 129 gets its update request denied

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#63]
Browser: Chrome
In admin mode, I refused the update request for collection 129. I got the following PHP warning message when I clicked on "Enviar": 
![image](https://cloud.githubusercontent.com/assets/17710971/15250127/d2b10db2-18e8-11e6-9e34-d66ab51ee6a0.png)

![image](https://cloud.githubusercontent.com/assets/17710971/15250146/ed6e1c1c-18e8-11e6-8606-29bf5aa9df6f.png)

2016-05-13 08:53:42 Apache/2.4.6 (CentOS) PHP/5.6.17 Yii Framework/1.1.13

When I click "Guardar", the form gets saved with no issues. Before mistakes related to denying update requests where linked to both "Guardar" and "Enviar". Hopefully this helps somehow

**Comment by jag2kn** [comment]
Este bug parece ser problema de la conexión de smtp que se tenía con gmail, revisando este proceso en otras colecciones el correo se envía correctamente

**Comment by AngelaCelis** [comment]
Solved by Lumon.
