### ISSUE TITLE
Error when trying to access the History for collection 86

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#64]
In the following screen, after I clic on "Selecccionar":
![image](https://cloud.githubusercontent.com/assets/17710971/15251401/d0ed84b4-18ee-11e6-8baa-06536601f5af.png)

I get this error message:
![image](https://cloud.githubusercontent.com/assets/17710971/15251415/e5888f9a-18ee-11e6-9ed8-dc3829b0e77b.png)

**Comment by jag2kn** [comment]
El registro de colección 086 fue actualizado con el numero 44 previamente

Y se evalúa que se pueden ver los archivos

![bug86](https://cloud.githubusercontent.com/assets/321637/22935668/3d6c8806-f2a1-11e6-80e1-c7668bf32ac5.png)

http://rnc.humboldt.org.co/admin/index.php/registros/listarHistoricosFolder?name=086_MHN-UC

**Comment by AngelaCelis** [comment]
Solved by Lumon.
