### ISSUE TITLE
Error message when downloading attached files from a contact form

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#65]
Browser: Chrome

http://rnc.humboldt.org.co/admin/index.php/pqrs/125
When I click on on the "Descargar" button I get the following message:
![image](https://cloud.githubusercontent.com/assets/17710971/15430099/693e1a42-1e69-11e6-97ad-1089261ee733.png)

**Comment by jag2kn** [comment]
Los archivos adjuntos se pueden enviar en el formulario de PQR desde la 146, probablemente por el link simbólico que se colocó en la raíz del sistema ```rnc_files```

**Comment by jag2kn** [comment]
Revisado

**Comment by AngelaCelis** [comment]
Solved by Lumon.
