### ISSUE TITLE
Datatables error 

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/rnc_app#66]
Reported by @jdmartinez89 on #32 

Browser: Chrome
This issue is happening again. When visualizing the update request I get the following message:
![image](https://cloud.githubusercontent.com/assets/17710971/15556051/64d005ca-2291-11e6-8bb5-2beb14911c0b.png)

**Comment by jag2kn** [comment]
Se resolvió al reimplementar el componente de curadores

**Comment by AngelaCelis** [comment]
Revisado.
