### ISSUE TITLE
When clicking on collection 198 update request files

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#67]
Browser: Chrome
The following message appears for all attached files after clicking "Ver" 
![image](https://cloud.githubusercontent.com/assets/17710971/15556423/672b5f3e-2293-11e6-993a-368bfe4466b4.png)

**Comment by jdmartinez89** [comment]
Same happens for new collection request "Colección limnológica (Perifiton, Fitoplancton, zooplancton y macroinvertebrados acuáticos M&L Consultores Ambientales SAS", acronym CLMYL
![image](https://cloud.githubusercontent.com/assets/17710971/15557390/499f1bd6-2298-11e6-9914-adbe5d7332f4.png)

**Comment by jdmartinez89** [comment]
Collection 191:
![image](https://cloud.githubusercontent.com/assets/17710971/15576045/7eab29cc-231b-11e6-9b66-38b8ae9116b7.png)

**Comment by jdmartinez89** [comment]
Collection 195:
![image](https://cloud.githubusercontent.com/assets/17710971/15581544/6285dbc2-2332-11e6-93df-2d3a80c5491b.png)

**Comment by jdmartinez89** [comment]
Same happens for new collection request "COLECCIÓN DE MICROORGANISMOS HALÓFILOS DE LA UNIVERSIDAD DE LA SABANA" acronym HALOFUSAB

**Comment by jag2kn** [comment]
Este problema sucedía por la falta del link simbólico de ```rnc_files``` en la carpeta raíz del servidor, fue solucionado el problema de adjuntar documentos cuando esto se solucionó.

En el caso de esta colección especifica se subieron posteriormente los archivos nuevamente y estos están en el servidor:

![adjuntos](https://cloud.githubusercontent.com/assets/321637/22936356/4099ff52-f2a3-11e6-9242-faf9278f6686.png)

**Comment by jag2kn** [comment]
Revisado

**Comment by AngelaCelis** [comment]
Solved by Lumon.
