### ISSUE TITLE
Error: Attached files for collection 191 are not visible

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#68]
Browser Chrome
When I log in as the user or as the admin, the attached files in "Documentos adjuntos" after clicking on "Seleccionar archivo" and choosing the files are displayed as fully uploaded, but when reviewing as admin I see nothing there.

**Comment by jag2kn** [comment]
se revisó el modulo y se valido para que el usuario pudiera subir los archivos

**Comment by AngelaCelis** [comment]
Solved by Lumon.
