### ISSUE TITLE
URLs that still have lumon domain when clicking the RNC logo

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#69]
http://rnc.humboldt.org.co/admin/index.php/admin/login
http://rnc.humboldt.org.co/admin/index.php/entidad/solicitud
http://rnc.humboldt.org.co/admin/index.php/registros/colecciones

**Comment by jdmartinez89** [comment]
The link is rncwp.lumon.com.co

**Comment by danipilze** [comment]
done!
