### ISSUE TITLE
I cant reject an actualization

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/rnc_app#71]
When I try to reject a form, appear this error:

![image](https://cloud.githubusercontent.com/assets/16558682/15932916/30c03d98-2e23-11e6-9326-8a2ab2007a4b.png)

**Comment by jag2kn** [comment]
Este problema es ocasionado por la validación de los datos. Se solucionó colocando los valores por defecto en las fechas de actualización y fecha colección

**Comment by jag2kn** [comment]
Revisado

**Comment by AngelaCelis** [comment]
Solved by Lumon.
