### ISSUE TITLE
Error when refusing a new user request

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#72]
PHP warning

fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known

/var/www/html/admin/protected/extensions/yii-mail/vendors/swiftMailer/classes/Swift/Transport/StreamBuffer.php(236)

224   private function _establishSocketConnection()
225   {
226     $host = $this->_params['host'];
227     if (!empty($this->_params['protocol']))
228     {
229       $host = $this->_params['protocol'] . '://' . $host;
230     }
231     $timeout = 15;
232     if (!empty($this->_params['timeout']))
233     {
234       $timeout = $this->_params['timeout'];
235     }
236     if (!$this->_stream = fsockopen($host, $this->_params['port'], $errno, $errstr, $timeout))
237     {
238       throw new Swift_TransportException(
239         'Connection could not be established with host ' . $this->_params['host'] .
240         ' [' . $errstr . ' #' . $errno . ']'
241         );
242     }
243     if (!empty($this->_params['blocking']))
244     {
245       stream_set_blocking($this->_stream, 1);
246     }
247     else
248     {
Stack Trace
#0

–  /var/www/html/admin/protected/extensions/yii-mail/vendors/swiftMailer/classes/Swift/Transport/StreamBuffer.php(236): fsockopen("ssl://smtp.gmail.com", 465, 0, "", ...)
231     $timeout = 15;
232     if (!empty($this->_params['timeout']))
233     {
234       $timeout = $this->_params['timeout'];
235     }
236     if (!$this->_stream = fsockopen($host, $this->_params['port'], $errno, $errstr, $timeout))
237     {
238       throw new Swift_TransportException(
239         'Connection could not be established with host ' . $this->_params['host'] .
240         ' [' . $errstr . ' #' . $errno . ']'
241         );
#1

–  /var/www/html/admin/protected/extensions/yii-mail/vendors/swiftMailer/classes/Swift/Transport/StreamBuffer.php(73): Swift_Transport_StreamBuffer->_establishSocketConnection()
68       case self::TYPE_PROCESS:
69         $this->_establishProcessConnection();
70         break;
71       case self::TYPE_SOCKET:
72       default:
73         $this->_establishSocketConnection();
74         break;
75     }
76   }
77  
78   /**
#2

–  /var/www/html/admin/protected/extensions/yii-mail/vendors/swiftMailer/classes/Swift/Transport/AbstractSmtpTransport.php(101): Swift_Transport_StreamBuffer->initialize(array("protocol" => "ssl", "host" => "smtp.gmail.com", "port" => 465, "timeout" => 30, ...))
096         }
097       }
098  
099       try
100       {
101         $this->_buffer->initialize($this->_getBufferParams());
102       }
103       catch (Swift_TransportException $e)
104       {
105         $this->_throwException($e);
106       }
#3
-  /var/www/html/admin/protected/extensions/yii-mail/vendors/swiftMailer/classes/Swift/Mailer.php(74): Swift_Transport_AbstractSmtpTransport->start()
  #4  
-  /var/www/html/admin/protected/extensions/yii-mail/YiiMail.php(133): Swift_Mailer->send(Swift_Message, array())
  #5  
-  /var/www/html/admin/protected/controllers/EntidadController.php(512): YiiMail->send(YiiMailMessage)
  #6  
  unknown(0): EntidadController->actionValidar("324")
  #7  
-  /var/www/framework/web/actions/CAction.php(108): ReflectionMethod->invokeArgs(EntidadController, array("324"))
  #8  
-  /var/www/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(EntidadController, ReflectionMethod, array("id" => "324"))
  #9  
-  /var/www/framework/web/CController.php(308): CInlineAction->runWithParams(array("id" => "324"))
  #10 
-  /var/www/framework/web/CController.php(286): CController->runAction(CInlineAction)
  #11 
-  /var/www/framework/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array())
  #12 
-  /var/www/framework/web/CWebApplication.php(282): CController->run("validar")
  #13 
-  /var/www/framework/web/CWebApplication.php(141): CWebApplication->runController("entidad/validar")
  #14 
-  /var/www/framework/base/CApplication.php(169): CWebApplication->processRequest()
  #15 
-  /var/www/html/admin/index.php(13): CApplication->run()
  2016-06-09 14:00:23 Apache/2.4.6 (CentOS) PHP/5.6.17 Yii Framework/1.1.13

**Comment by jag2kn** [comment]
En el momento de este error faltaba realizar la configuración del servidor para el parámetro ```hostname```

```php_network_getaddresses: getaddrinfo failed: Name or service not know```

Ya fue solucionado previamente

**Comment by jag2kn** [comment]
Revisado

**Comment by AngelaCelis** [comment]
Solved by Lumon.
