### ISSUE TITLE
In the list of Registered collections the SiB image links are not visible

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#76]
Browser Chrome:
In the list of Registered collections http://rnc.humboldt.org.co/admin/index.php/registros/colecciones , the SiB image links are not visible. Are the images stored in in the same database a historicals? Suppose this is related as well to #67 #75 #74 #73

**Comment by jag2kn** [comment]
Se ajustaron las rutas de las imágenes con el prefijo ```/admin```

**Comment by AngelaCelis** [comment]
Solved by Lumon
