### ISSUE TITLE
Error reported by user

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#77]
"He diligenciado los formatos y adjuntado los documentos soporte.  Y cuando doy enviar aparece un mensaje PHP Warning Adjunto el pantallazo"
![image](https://cloud.githubusercontent.com/assets/17710971/16490908/2f44fbc8-3ea1-11e6-81e7-07b2c68454b8.png)

**Comment by jag2kn** [comment]
Se reimplementó el registro de los curadores y el campo no es obligatorio

**Comment by AngelaCelis** [comment]
Solved by Lumon.
