### ISSUE TITLE
No curator information is stored for collection 197

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#78]
When the curator infromation is filled, saved and the request is sent, neither the admin nor the user can see any indormation in the curators data table.
http://rnc.humboldt.org.co/admin/index.php/registros/validar/1019

**Comment by jag2kn** [comment]
Se revisó la información y ya se ve almacenada la información del curador en esta colección

**Comment by AngelaCelis** [comment]
Solved by Lumon.
