### ISSUE TITLE
Error: when viewing the detail of an accepted update form

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#79]
Browser: Chrome

When viewing the detail of an accepted update form for example in http://rnc.humboldt.org.co/admin/index.php/registros/viewDetail/16
I click on the number 2 button as show in the picture: 
![image](https://cloud.githubusercontent.com/assets/17710971/17178641/dc0778fa-53db-11e6-9b34-3fa4bfafe3c4.png)
and get sent back to the firts tab of the form. Then having to click in the proper tab and scroll down all the way back to what I was looking at.

Please correct the link and actions triggered by the button.

**Comment by jag2kn** [comment]
Se soluciona este link activando jquery-datatable para que funcione en ajax la tabla, y además se evalúan los parámetros get en la carga de la pagina y si tiene cambio de paginación se activa el tab2 por defecto

**Comment by AngelaCelis** [comment]
Solved by Lumon.
