### ISSUE TITLE
When a new collection certificate is generated

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#80]
If the information for the collection surpasses a certain length the certificate can have two pages and looks very bad.
http://rnc.humboldt.org.co/rnc_files/Certificados/ColOrni-Choc%C3%B3/certificado_rnc_276.pdf

**Comment by jag2kn** [comment]
En la generación de nuevos certificados se genera correctamente

http://rnc.humboldt.org.co/rnc_files/Certificados/prueba/certificado_rnc_349.pdf

**Comment by AngelaCelis** [comment]
Solved by Lumon.
