### ISSUE TITLE
Error When trying to delete a duplicate update form

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#81]
Browser: Chrome
![image](https://cloud.githubusercontent.com/assets/17710971/17532793/d5c85862-5e47-11e6-9a63-cb194aaffc03.png)
URL: http://rnc.humboldt.org.co/admin/index.php/registros/81?status=Ok
Error message:
![image](https://cloud.githubusercontent.com/assets/17710971/17532928/60ef0f12-5e48-11e6-90ed-aa5f964c6b59.png)

**Comment by jag2kn** [comment]
Los formularios de actualización si se pueden eliminar.

El que no se puede borrar y toca colocar un mensaje es en el formulario de registro de la colección.
Mensaje: "No se puede borrar el formulario de Registro de la Colección"

**Comment by jag2kn** [comment]
Implementado

![borrarregistrobase](https://cloud.githubusercontent.com/assets/321637/23002146/271d8d0e-f3b7-11e6-9eb4-ba7f3337977f.png)

**Comment by AngelaCelis** [comment]
Solved by Lumon.
