### ISSUE TITLE
Error. There is field called "Tipo de institución" which can't be modified

### ISSUE THREAD

**Issue by jdmartinez89** [SIB-Colombia/rnc_app#82]
In the update requests, for the TITULA information, when viewing the summary of an approved collection the last field is called "Tipo de institución", but when filling up the update request form there is no such field, so no collections can update that value

**Comment by jag2kn** [comment]
Campo agregado en el formulario y validado para que se almacenen los cambios

**Comment by AngelaCelis** [comment]
Solved by Lumon.
