### ISSUE TITLE
Problem with the link to Curators Directory Error 500

### ISSUE THREAD

**Issue by AngelaCelis** [SIB-Colombia/rnc_app#86]
http://rnc.humboldt.org.co/admin/index.php/Curador/Especialista

![directorio](https://cloud.githubusercontent.com/assets/9890635/20192402/af90eb6a-a757-11e6-9ffe-e9ec208828c4.PNG)

**Comment by jag2kn** [comment]
Se solucionó validando el campo subgrupo_taxonomico cuando es nulo colocando una cadena vacía

**Comment by AngelaCelis** [comment]
Solved by Lumon.
