### ISSUE TITLE
Error 500 curadores_table

### ISSUE THREAD

**Issue by AngelaCelis** [SIB-Colombia/rnc_app#87]
When the formulary of the collection 184 is opened appears the following error, attached in the image "Curadores":
![curadores](https://cloud.githubusercontent.com/assets/9890635/20566521/64363aba-b163-11e6-90b7-7df042905f54.PNG)
![error500curadores](https://cloud.githubusercontent.com/assets/9890635/20566613/a8cfda64-b163-11e6-9c7a-10893f036ca0.PNG)
Any modification made on the curadores table isn´t stored.

**Comment by jag2kn** [comment]
Solucionado al reimplementar la edición de curadores

**Comment by AngelaCelis** [comment]
Solved by Lumon.
