### ISSUE TITLE
Problem attaching certificates

### ISSUE THREAD

**Issue by AngelaCelis** [SIB-Colombia/rnc_app#88]
The app doesn't allow to attach certificates in the actualization process, it just allow it for new registers.
![attachmentcertificates](https://cloud.githubusercontent.com/assets/9890635/20600739/14fb7166-b223-11e6-8958-4d031421b322.PNG)

**Comment by jag2kn** [comment]
Se configuró el siguiente comportamiento:
 * Si se seleccionan documentos los envía adjuntos
 * Si se genera un certificado lo adjunta

**Comment by jag2kn** [comment]
Se envían los documentos que se coloquen adjuntos y se guarda en la lista de certificados para que quede en el registro de archivos

**Comment by AngelaCelis** [comment]
Solved by Lumon.
