### ISSUE TITLE
Error 500 when sending or saving a New register

### ISSUE THREAD

**Issue by AngelaCelis** [SIB-Colombia/rnc_app#89]
The problem occurs when we try to send or save the formulary of  the new register of the collection Banco de Germoplasma Vegetal Corpoica. 

DbCommand falló al ejecutar la sentencia SQL: SQLSTATE[HY000]: General error: 1364 Field 'registros_id' doesn't have a default value. The SQL statement executed was: INSERT INTO `registros_update` (`departamento_id`, `ciudad_id`, `estado`, `registro_id`, `tamano_coleccion_total`, `tipo_coleccion_total`, `aprobado`, `nombre`, `acronimo`, `fecha_fund`, `descripcion`, `telefono`, `email`, `direccion`, `Latitud`, `Longitud`, `cobertura_tax`, `cobertura_geog`, `cobertura_temp`, `deorreferenciados`, `sistematizacion`, `ej_tipo_cantidad`, `listado_anexos`, `info_adicional`, `terminos`, `contactos_id`, `dilegenciadores_id`, `fecha_env`, `ejemplar_tipo`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13, :yp14, :yp15, :yp16, :yp17, :yp18, :yp19, :yp20, :yp21, :yp22, :yp23, :yp24, :yp25, :yp26, :yp27, :yp28). Bound with :yp0='CO-CUN', :yp1='25473', :yp2=0, :yp3=0, :yp4=0, :yp5=0, :yp6=1, :yp7='Colección Banco de germoplasma Vegetal - Corpoica ', :yp8='BGVC', :yp9=1904, :yp10='El BGVC lo administra Corpoica. El Banco inicialmente representaba colecciones de trabajo para mejoramiento vegetal. A partir de los años 90, el banco se organizó y se hizo curaduría para enfocarse en seguridad alimentaria e investigación agrícola', :yp11='57 + 1 4 22 73 00 ', :yp12='propiedadintelectual@corpoica.org.co', :yp13='Kilometro 14 via Mosquera ', :yp14='-74.204900755', :yp15='74.2307', :yp16='Bixa, Canna, Capsicum, Annona, Eugenia, Arracacia, Euterpe, Ipomea, Theobroma, Myrciaria, Cucurbita, Gynerium, Bactris, Solanum, Cocos, Elaeis, Phaseolus, Psidium, Lupinus, Vaccinium, Discorea, Rubus, Cyphomandra, Carica, Vasconcellea, Passiflora, Plukenetia, Physalis, Smallanthus', :yp17='Nacional ', :yp18='1994', :yp19='5', :yp20='Excel ', :yp21=NULL, :yp22='Solicitud de creación cedula representante existencia listado especímenes ', :yp23='', :yp24=1, :yp25=1195, :yp26=1710, :yp27='2016-11-17 14:53:12', :yp28=1

**Comment by jag2kn** [comment]
Se colocó el valor por defecto en 0 para los nuevos registros

**Comment by AngelaCelis** [comment]
Solved by Lumon.
