### ISSUE TITLE
Error en el url de archivo adjunto

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/rnc_app#91]
Se está apuntando a:
http://rncwp.lumon.com.co/wp-content/uploads/2016/03/InstructivoRNC2.0.2.pdf

Debe apuntar a:
http://rnc.humboldt.org.co/wp/wp-content/uploads/2016/03/InstructivoRNC2.0.2.pdf

**Comment by jag2kn** [comment]
Solucionado dentro de Wordpress

http://rnc.humboldt.org.co/wp/registro-y-actualizacion/

**Comment by AngelaCelis** [comment]
Solved by Lumon.
