### ISSUE TITLE
Posibilidad de edición de curadores previo al envío rol usuario

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/rnc_app#93]
Cuando se esta registrando o actualizando una colección antes de "enviar" el objetivo es que el usuario pueda modificar los curadores 

http://rnc.humboldt.org.co/admin/index.php/registros/index

Botones para editar o eliminar
http://rnc.humboldt.org.co/admin/index.php/registros/updateDetail/974

**Comment by jag2kn** [comment]
Solucionado

**Comment by AngelaCelis** [comment]
Solved by Lumon.
