### ISSUE TITLE
Posibilidad de edición de curadores previo al envío rol administrador

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/rnc_app#94]
Que el usuario administrador pueda editar la lista de curadores

http://rnc.humboldt.org.co/admin/index.php/registros/index

Botones para editar o eliminar
http://rnc.humboldt.org.co/admin/index.php/registros/updateDetail/974

**Comment by jag2kn** [comment]
Solucionado

**Comment by AngelaCelis** [comment]
Solved by Lumon.
