### ISSUE TITLE
Posibilidad de eliminar archivos adjuntos por parte del rol administrador

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/rnc_app#95]
Que el usuario administrador pueda eliminar archivos adjuntos

http://rnc.humboldt.org.co/admin/index.php/registros/validar/953

**Comment by jag2kn** [comment]
Se habilita en modo edición del formulario la opción para borrar los archivos
Se agrega confirmación a la eliminación de archivos
Se mejora los estilos de los botones

**Comment by AngelaCelis** [comment]
Solved by Lumon.
