### ISSUE TITLE
Cuando es actualización de registro en Aprobar ver Archivo Certificado

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/rnc_app#97]
No esta adjuntando el archivo cuando se envía el formulario en "Archivo Certificado"

http://rnc.humboldt.org.co/admin/index.php/registros/validar/953

Este archivo debe quedar en el histórico

Menú > Colecciones / Certificados

**Comment by jag2kn** [comment]
Se realiza una copia del archivo en el registro de historicos

**Comment by AngelaCelis** [comment]
Solved by Lumon.
