### ISSUE TITLE
Error al enviar formulario de registro de nueva colección

### ISSUE THREAD

**Issue by AngelaCelis** [SIB-Colombia/rnc_app#98]
![image](https://cloud.githubusercontent.com/assets/9890635/21141066/2f53e68e-c109-11e6-9177-7a7c3da86773.png)

**Comment by jag2kn** [comment]
Se solucionó realizando diferentes procesos de validación garantizando que los datos lleguen completos al servidor

**Comment by AngelaCelis** [comment]
Solved by Lumon.
