### ISSUE TITLE
El sistema de PQR no permite descartar solicitudes

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/rnc_app#99]
Cuando una solicitud llega duplicada o ha sido respondida por otro medio queda en la lista de pqr y es obligatorio responderle nuevamente al usuario, generando en algunos casos correos innecesarios o no deseados a este.

**Comment by jag2kn** [comment]
Se crea un nuevo botón para descartar la solicitud y se marca como cerrado el caso.

**Comment by AngelaCelis** [comment]
Solved by Lumon
